/**
 * Juramentos do Styx — click/all ×2–×5; clickKSps (% SPS); geradores ×2 ou ×5 (catch-up T1–T3).
 * Resetam no Lethe.
 */

function freezeRequires(requires = {}) {
  const next = { ...requires };
  if (Array.isArray(requires.allUpgradeIds)) {
    next.allUpgradeIds = Object.freeze([...requires.allUpgradeIds]);
  }
  return Object.freeze(next);
}

function freezeAll(list) {
  return Object.freeze(list.map((item) => Object.freeze({
    ...item,
    requires: freezeRequires(item.requires),
  })));
}

export const UPGRADES = freezeAll([
  {
    id: 'foice_afilada',
    name: 'Foice Afiada',
    cost: '100',
    kind: 'clickMult',
    factor: '2',
    requires: { minSouls: '0' },
  },
  {
    id: 'juramento_acheron',
    name: 'Juramento do Acheron',
    cost: '500',
    kind: 'clickMult',
    factor: '2',
    requires: { upgradeId: 'foice_afilada', minSouls: '0' },
  },
  {
    id: 'pacto_das_margens',
    name: 'Pacto das Margens',
    cost: '2500',
    kind: 'clickMult',
    factor: '2',
    requires: { upgradeId: 'juramento_acheron', minSouls: '0' },
  },
  {
    id: 'ceifador_ctoniano',
    name: 'Ceifador Ctoniano',
    cost: '10000',
    kind: 'clickMult',
    factor: '2',
    requires: { upgradeId: 'pacto_das_margens', minSouls: '0' },
  },
  {
    id: 'colheita_eterna',
    name: 'Colheita Eterna',
    cost: '50000',
    kind: 'clickMult',
    factor: '2',
    requires: { upgradeId: 'ceifador_ctoniano', minSouls: '0' },
  },
  {
    id: 'fio_da_foice',
    name: 'Fio da Foice',
    cost: '250000',
    kind: 'clickMult',
    factor: '2',
    requires: { upgradeId: 'colheita_eterna', minSouls: '0' },
  },
  {
    id: 'lamina_do_styx',
    name: 'Lâmina do Styx',
    cost: '1250000',
    kind: 'clickMult',
    factor: '2',
    requires: { upgradeId: 'fio_da_foice', minSouls: '0' },
  },
  {
    id: 'ceifa_das_almas',
    name: 'Ceifa das Almas',
    cost: '6250000',
    kind: 'clickMult',
    factor: '5',
    requires: { upgradeId: 'lamina_do_styx', minSouls: '0' },
  },
  {
    id: 'pacto_do_corte',
    name: 'Pacto do Corte',
    cost: '31250000',
    kind: 'clickMult',
    factor: '5',
    requires: { upgradeId: 'ceifa_das_almas', minSouls: '0' },
  },
  {
    id: 'eco_da_foice',
    name: 'Eco da Foice',
    cost: '100000000',
    kind: 'clickKSps',
    factor: '0.01',
    requires: { upgradeId: 'pacto_do_corte', minSouls: '0' },
  },
  {
    id: 'danca_da_morte',
    name: 'Dança da Morte',
    cost: '500000000',
    kind: 'clickMult',
    factor: '2',
    requires: { upgradeId: 'eco_da_foice', minSouls: '0' },
  },
  {
    id: 'colheita_absoluta',
    name: 'Colheita Absoluta',
    cost: '2500000000',
    kind: 'clickMult',
    factor: '5',
    requires: { upgradeId: 'danca_da_morte', minSouls: '0' },
  },
  // --- T1 Sombra Vagante ---
  {
    id: 'umbras_despertas',
    name: 'Umbras Despertas',
    cost: '100',
    kind: 'generatorMult',
    factor: '2',
    generatorId: 'wandering_shade',
    requires: { generatorId: 'wandering_shade', quantity: 1 },
  },
  {
    id: 'cortejo_das_sombras',
    name: 'Cortejo das Sombras',
    cost: '500',
    kind: 'generatorMult',
    factor: '2',
    generatorId: 'wandering_shade',
    requires: { generatorId: 'wandering_shade', quantity: 10 },
  },
  {
    id: 'legiao_das_umbras',
    name: 'Legião das Umbras',
    cost: '5000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'wandering_shade',
    requires: { generatorId: 'wandering_shade', quantity: 25 },
  },
  {
    id: 'mare_de_sombras',
    name: 'Maré de Sombras',
    cost: '50000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'wandering_shade',
    requires: { generatorId: 'wandering_shade', quantity: 50 },
  },
  {
    id: 'eclipse_do_acheron',
    name: 'Eclipse do Acheron',
    cost: '500000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'wandering_shade',
    requires: { generatorId: 'wandering_shade', quantity: 100 },
  },
  {
    id: 'cortejo_infinito',
    name: 'Cortejo Infinito',
    cost: '5000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'wandering_shade',
    requires: { generatorId: 'wandering_shade', quantity: 150 },
  },
  {
    id: 'noite_sem_fim',
    name: 'Noite Sem Fim',
    cost: '50000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'wandering_shade',
    requires: { generatorId: 'wandering_shade', quantity: 200 },
  },
  // --- T2 Servos de Caronte ---
  {
    id: 'moeda_no_barquinho',
    name: 'Moeda no Barquinho',
    cost: '1000',
    kind: 'generatorMult',
    factor: '2',
    generatorId: 'charon_servants',
    requires: { generatorId: 'charon_servants', quantity: 1 },
  },
  {
    id: 'frota_de_caronte',
    name: 'Frota de Caronte',
    cost: '5000',
    kind: 'generatorMult',
    factor: '2',
    generatorId: 'charon_servants',
    requires: { generatorId: 'charon_servants', quantity: 10 },
  },
  {
    id: 'remadores_do_styx',
    name: 'Remadores do Styx',
    cost: '50000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'charon_servants',
    requires: { generatorId: 'charon_servants', quantity: 25 },
  },
  {
    id: 'armada_das_margens',
    name: 'Armada das Margens',
    cost: '500000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'charon_servants',
    requires: { generatorId: 'charon_servants', quantity: 50 },
  },
  {
    id: 'travessia_eterna',
    name: 'Travessia Eterna',
    cost: '5000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'charon_servants',
    requires: { generatorId: 'charon_servants', quantity: 100 },
  },
  {
    id: 'porto_das_cem_barcas',
    name: 'Porto das Cem Barcas',
    cost: '50000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'charon_servants',
    requires: { generatorId: 'charon_servants', quantity: 150 },
  },
  {
    id: 'mar_de_obolos',
    name: 'Mar de Óbolos',
    cost: '500000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'charon_servants',
    requires: { generatorId: 'charon_servants', quantity: 200 },
  },
  // --- T3 Cão Cerberiano ---
  {
    id: 'trela_cerberiana',
    name: 'Trela Cerberiana',
    cost: '11000',
    kind: 'generatorMult',
    factor: '2',
    generatorId: 'cerberian_hound',
    requires: { generatorId: 'cerberian_hound', quantity: 1 },
  },
  {
    id: 'tres_cabecas',
    name: 'Três Cabeças',
    cost: '55000',
    kind: 'generatorMult',
    factor: '2',
    generatorId: 'cerberian_hound',
    requires: { generatorId: 'cerberian_hound', quantity: 10 },
  },
  {
    id: 'matilha_do_ade',
    name: 'Matilha do Ade',
    cost: '550000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'cerberian_hound',
    requires: { generatorId: 'cerberian_hound', quantity: 25 },
  },
  {
    id: 'guardiao_triplo',
    name: 'Guardião Triplo',
    cost: '5500000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'cerberian_hound',
    requires: { generatorId: 'cerberian_hound', quantity: 50 },
  },
  {
    id: 'canil_do_tartaro',
    name: 'Canil do Tártaro',
    cost: '55000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'cerberian_hound',
    requires: { generatorId: 'cerberian_hound', quantity: 100 },
  },
  {
    id: 'uivo_das_portas',
    name: 'Uivo das Portas',
    cost: '550000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'cerberian_hound',
    requires: { generatorId: 'cerberian_hound', quantity: 150 },
  },
  {
    id: 'fome_sem_fim',
    name: 'Fome Sem Fim',
    cost: '5500000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'cerberian_hound',
    requires: { generatorId: 'cerberian_hound', quantity: 200 },
  },
  // --- T4 Juiz do Tártaro ---
  {
    id: 'veredito_tartaro',
    name: 'Veredito do Tártaro',
    cost: '120000',
    kind: 'generatorMult',
    factor: '2',
    generatorId: 'tartarus_judge',
    requires: { generatorId: 'tartarus_judge', quantity: 1 },
  },
  {
    id: 'lei_inquebravel',
    name: 'Lei Inquebrável',
    cost: '600000',
    kind: 'generatorMult',
    factor: '2',
    generatorId: 'tartarus_judge',
    requires: { generatorId: 'tartarus_judge', quantity: 10 },
  },
  {
    id: 'banco_dos_juizes',
    name: 'Banco dos Juízes',
    cost: '6000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'tartarus_judge',
    requires: { generatorId: 'tartarus_judge', quantity: 25 },
  },
  {
    id: 'codigo_das_profundezas',
    name: 'Código das Profundezas',
    cost: '60000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'tartarus_judge',
    requires: { generatorId: 'tartarus_judge', quantity: 50 },
  },
  {
    id: 'sentenca_coletiva',
    name: 'Sentença Coletiva',
    cost: '600000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'tartarus_judge',
    requires: { generatorId: 'tartarus_judge', quantity: 100 },
  },
  {
    id: 'colegio_infernus',
    name: 'Colégio Infernus',
    cost: '3000000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'tartarus_judge',
    requires: { generatorId: 'tartarus_judge', quantity: 150 },
  },
  {
    id: 'lei_do_abismo',
    name: 'Lei do Abismo',
    cost: '15000000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'tartarus_judge',
    requires: { generatorId: 'tartarus_judge', quantity: 200 },
  },
  // --- T5 Forja de Phlegethon ---
  {
    id: 'brasa_phlegethon',
    name: 'Brasa de Phlegethon',
    cost: '1300000',
    kind: 'generatorMult',
    factor: '2',
    generatorId: 'phlegethon_forge',
    requires: { generatorId: 'phlegethon_forge', quantity: 1 },
  },
  {
    id: 'fornalha_industrial',
    name: 'Fornalha Industrial',
    cost: '6500000',
    kind: 'generatorMult',
    factor: '2',
    generatorId: 'phlegethon_forge',
    requires: { generatorId: 'phlegethon_forge', quantity: 10 },
  },
  {
    id: 'caldeiras_gemeas',
    name: 'Caldeiras Gêmeas',
    cost: '65000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'phlegethon_forge',
    requires: { generatorId: 'phlegethon_forge', quantity: 25 },
  },
  {
    id: 'rio_de_ferro',
    name: 'Rio de Ferro',
    cost: '650000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'phlegethon_forge',
    requires: { generatorId: 'phlegethon_forge', quantity: 50 },
  },
  {
    id: 'fundicao_eterna',
    name: 'Fundição Eterna',
    cost: '6500000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'phlegethon_forge',
    requires: { generatorId: 'phlegethon_forge', quantity: 100 },
  },
  {
    id: 'cinzas_do_rio',
    name: 'Cinzas do Rio',
    cost: '32500000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'phlegethon_forge',
    requires: { generatorId: 'phlegethon_forge', quantity: 150 },
  },
  {
    id: 'coracao_de_magma',
    name: 'Coração de Magma',
    cost: '162500000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'phlegethon_forge',
    requires: { generatorId: 'phlegethon_forge', quantity: 200 },
  },
  // --- T6 Trono de Obsidiana ---
  {
    id: 'cetro_obsidiana',
    name: 'Cetro de Obsidiana',
    cost: '14000000',
    kind: 'generatorMult',
    factor: '2',
    generatorId: 'obsidian_throne',
    requires: { generatorId: 'obsidian_throne', quantity: 1 },
  },
  {
    id: 'soberania_absoluta',
    name: 'Soberania Absoluta',
    cost: '70000000',
    kind: 'generatorMult',
    factor: '2',
    generatorId: 'obsidian_throne',
    requires: { generatorId: 'obsidian_throne', quantity: 10 },
  },
  {
    id: 'corte_obsidiana',
    name: 'Corte Obsidiana',
    cost: '700000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'obsidian_throne',
    requires: { generatorId: 'obsidian_throne', quantity: 25 },
  },
  {
    id: 'dominio_ctoniano',
    name: 'Domínio Ctoniano',
    cost: '7000000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'obsidian_throne',
    requires: { generatorId: 'obsidian_throne', quantity: 50 },
  },
  {
    id: 'imperio_sem_sol',
    name: 'Império Sem Sol',
    cost: '70000000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'obsidian_throne',
    requires: { generatorId: 'obsidian_throne', quantity: 100 },
  },
  {
    id: 'trono_sem_fim',
    name: 'Trono Sem Fim',
    cost: '350000000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'obsidian_throne',
    requires: { generatorId: 'obsidian_throne', quantity: 150 },
  },
  {
    id: 'noite_do_imperador',
    name: 'Noite do Imperador',
    cost: '1750000000000',
    kind: 'generatorMult',
    factor: '5',
    generatorId: 'obsidian_throne',
    requires: { generatorId: 'obsidian_throne', quantity: 200 },
  },
  {
    id: 'coroacao_imperador',
    name: 'Coroação do Imperador',
    cost: '1000000',
    kind: 'allGeneratorsMult',
    factor: '2',
    requires: { minSouls: '0' },
  },
  {
    id: 'rios_unificados',
    name: 'Rios Unificados',
    cost: '100000000',
    kind: 'allGeneratorsMult',
    factor: '2',
    requires: { minSouls: '0' },
  },
]);

export const UPGRADE_IDS = Object.freeze(UPGRADES.map((item) => item.id));

export const UPGRADE_BY_ID = Object.freeze(
  Object.fromEntries(UPGRADES.map((item) => [item.id, item])),
);

export function getUpgrade(id) {
  return UPGRADE_BY_ID[id] ?? null;
}

export function isKnownUpgradeId(id) {
  return Object.prototype.hasOwnProperty.call(UPGRADE_BY_ID, id);
}
