-- Migração 2026-09-21
-- Objetivo: TTL de sessões + rate limit de login/register
-- (Task 2 — docs/plano-ops-nav-email-perf-admin.md)

-- Sessões: expiração deslizante (14 dias; renovação se restam < 7 dias).
ALTER TABLE sessions
  ADD COLUMN IF NOT EXISTS expires_at timestamptz;

-- Backfill: sessões antigas ganham 14 dias a partir de created_at (ou now).
UPDATE sessions
SET expires_at = COALESCE(created_at, now()) + interval '14 days'
WHERE expires_at IS NULL;

ALTER TABLE sessions
  ALTER COLUMN expires_at SET DEFAULT (now() + interval '14 days');

CREATE INDEX IF NOT EXISTS sessions_expires_at_idx
  ON sessions (expires_at);

-- Rate limit persistido (serverless não tem memória estável entre invocações).
CREATE TABLE IF NOT EXISTS auth_rate_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action text NOT NULL CHECK (action IN ('login', 'register')),
  ip_hash text NOT NULL,
  username_hash text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS auth_rate_events_ip_created_idx
  ON auth_rate_events (action, ip_hash, created_at DESC);

CREATE INDEX IF NOT EXISTS auth_rate_events_user_created_idx
  ON auth_rate_events (action, username_hash, created_at DESC)
  WHERE username_hash IS NOT NULL;
