-- Migração 2026-09-08 (c)
-- Objetivo: clone de notas reveladas + eventos ao dono (velar/clonar)

ALTER TABLE user_notes
  ADD COLUMN IF NOT EXISTS cloned_from_note_id integer
    REFERENCES user_notes(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS user_notes_cloned_from_idx
  ON user_notes (cloned_from_note_id)
  WHERE cloned_from_note_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS user_note_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note_id integer NOT NULL REFERENCES user_notes(id) ON DELETE CASCADE,
  actor_user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  read_at timestamptz NULL,
  CONSTRAINT user_note_events_kind_chk CHECK (
    kind IN ('veiled_by_recipient', 'cloned_by', 'veiled_by_owner')
  )
);

CREATE INDEX IF NOT EXISTS user_note_events_note_created_idx
  ON user_note_events (note_id, created_at DESC);

CREATE INDEX IF NOT EXISTS user_note_events_note_unread_idx
  ON user_note_events (note_id)
  WHERE read_at IS NULL;
