-- Migração 2026-09-08 (b)
-- Objetivo: Grimório Pessoal (anotações do aluno + compartilhamento com companheiros)

CREATE TABLE IF NOT EXISTS user_notes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title text NOT NULL,
  body text NOT NULL DEFAULT '',
  pinned boolean NOT NULL DEFAULT false,
  tags jsonb NOT NULL DEFAULT '[]'::jsonb,
  lesson_id text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_notes_title_len_chk CHECK (char_length(title) BETWEEN 1 AND 120),
  CONSTRAINT user_notes_body_len_chk CHECK (char_length(body) <= 8000)
);

CREATE INDEX IF NOT EXISTS user_notes_user_updated_idx
  ON user_notes (user_id, pinned DESC, updated_at DESC);

CREATE INDEX IF NOT EXISTS user_notes_user_lesson_idx
  ON user_notes (user_id, lesson_id);

CREATE TABLE IF NOT EXISTS user_note_shares (
  note_id integer NOT NULL REFERENCES user_notes(id) ON DELETE CASCADE,
  shared_with_user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (note_id, shared_with_user_id)
);

CREATE INDEX IF NOT EXISTS user_note_shares_viewer_idx
  ON user_note_shares (shared_with_user_id, note_id);
