-- Migração 2026-09-22
-- Objetivo: audit log de mutações do Mestre (Espelho da Alma — Task 7)
-- docs/plano-ops-nav-email-perf-admin.md

CREATE TABLE IF NOT EXISTS admin_audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  target_user_id integer REFERENCES users(id) ON DELETE SET NULL,
  action text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS admin_audit_events_created_idx
  ON admin_audit_events (created_at DESC);

CREATE INDEX IF NOT EXISTS admin_audit_events_target_idx
  ON admin_audit_events (target_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS admin_audit_events_actor_idx
  ON admin_audit_events (actor_id, created_at DESC);
