-- Migração 2026-10-05
-- Aula 07: duplas por aula + diário de desenvolvimento compartilhado

CREATE TABLE IF NOT EXISTS lesson_duos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id text NOT NULL,
  requester_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  addressee_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'accepted')),
  requester_role text NULL
    CHECK (requester_role IS NULL OR requester_role IN ('arte', 'programacao')),
  addressee_role text NULL
    CHECK (addressee_role IS NULL OR addressee_role IN ('arte', 'programacao')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT lesson_duos_no_self_chk CHECK (requester_id <> addressee_id),
  CONSTRAINT lesson_duos_pair_uidx UNIQUE (lesson_id, requester_id, addressee_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS lesson_duos_unordered_pair_uidx
  ON lesson_duos (
    lesson_id,
    LEAST(requester_id, addressee_id),
    GREATEST(requester_id, addressee_id)
  );

CREATE UNIQUE INDEX IF NOT EXISTS lesson_duos_accepted_requester_uidx
  ON lesson_duos (lesson_id, requester_id)
  WHERE status = 'accepted';

CREATE UNIQUE INDEX IF NOT EXISTS lesson_duos_accepted_addressee_uidx
  ON lesson_duos (lesson_id, addressee_id)
  WHERE status = 'accepted';

CREATE INDEX IF NOT EXISTS lesson_duos_requester_status_idx
  ON lesson_duos (lesson_id, requester_id, status);

CREATE INDEX IF NOT EXISTS lesson_duos_addressee_status_idx
  ON lesson_duos (lesson_id, addressee_id, status);

CREATE TABLE IF NOT EXISTS lesson_journals (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id text NOT NULL,
  duo_id integer NULL REFERENCES lesson_duos(id) ON DELETE CASCADE,
  owner_user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  partner_user_id integer NULL REFERENCES users(id) ON DELETE SET NULL,
  body text NOT NULL DEFAULT '',
  revision integer NOT NULL DEFAULT 1,
  updated_by integer NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS lesson_journals_solo_uidx
  ON lesson_journals (lesson_id, owner_user_id)
  WHERE duo_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS lesson_journals_duo_uidx
  ON lesson_journals (duo_id)
  WHERE duo_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS lesson_journals_lesson_owner_idx
  ON lesson_journals (lesson_id, owner_user_id);
