-- Migração 2026-09-10
-- Objetivo: e-mail no aluno + tokens de verificação / reset de senha
-- (Fase 1 — docs/plano-esqueci-senha-email.md)
--
-- email é nullable: contas antigas e admin não quebram.
-- Cadastro novo passa a preencher sempre (Fase 2).

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS email_verified_at timestamptz NULL;

-- Impede selo confirmado sem endereço, e string vazia como “e-mail preenchido”
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'users_email_verified_requires_email_chk'
  ) THEN
    ALTER TABLE users
      ADD CONSTRAINT users_email_verified_requires_email_chk
      CHECK (email_verified_at IS NULL OR email IS NOT NULL);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'users_email_nonempty_chk'
  ) THEN
    ALTER TABLE users
      ADD CONSTRAINT users_email_nonempty_chk
      CHECK (email IS NULL OR char_length(btrim(email)) > 0);
  END IF;
END $$;

-- Único quando preenchido; case-insensitive
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_uidx
  ON users (lower(email))
  WHERE email IS NOT NULL AND btrim(email) <> '';

-- Reset de Palavra + confirmação de selo (uma tabela, dois purposes)
CREATE TABLE IF NOT EXISTS auth_email_tokens (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  purpose text NOT NULL
    CHECK (purpose IN ('reset_password', 'verify_email')),
  token_hash text NOT NULL UNIQUE,
  email text NOT NULL,
  requested_ip text NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS auth_email_tokens_user_purpose_created_idx
  ON auth_email_tokens (user_id, purpose, created_at DESC);

CREATE INDEX IF NOT EXISTS auth_email_tokens_expires_idx
  ON auth_email_tokens (expires_at);

-- Rate limit (Fases 2–3): pedidos por e-mail e por IP na última hora
CREATE INDEX IF NOT EXISTS auth_email_tokens_email_purpose_created_idx
  ON auth_email_tokens (lower(email), purpose, created_at DESC);

CREATE INDEX IF NOT EXISTS auth_email_tokens_ip_created_idx
  ON auth_email_tokens (requested_ip, created_at DESC)
  WHERE requested_ip IS NOT NULL;
