-- Migração 2026-09-08
-- Objetivo: vínculos entre alunos (Companheiros de Jornada)

CREATE TABLE IF NOT EXISTS friendships (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  addressee_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'accepted')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT friendships_no_self_chk CHECK (requester_id <> addressee_id),
  CONSTRAINT friendships_pair_uidx UNIQUE (requester_id, addressee_id)
);

-- Impede A→B e B→A ao mesmo tempo (um único laço por par de usuários)
CREATE UNIQUE INDEX IF NOT EXISTS friendships_unordered_pair_uidx
  ON friendships (LEAST(requester_id, addressee_id), GREATEST(requester_id, addressee_id));

CREATE INDEX IF NOT EXISTS friendships_requester_status_idx
  ON friendships (requester_id, status);

CREATE INDEX IF NOT EXISTS friendships_addressee_status_idx
  ON friendships (addressee_id, status);
