-- Migração 2026-09-22
-- Objetivo: Códigos de Recuperação da Alma (por aluno, uso único, TTL 24h)
-- Task 3 — docs/plano-email-opcional-recuperacao-admin.md

CREATE TABLE IF NOT EXISTS soul_recovery_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code_hash text NOT NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_by integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS soul_recovery_codes_user_active_idx
  ON soul_recovery_codes (user_id)
  WHERE used_at IS NULL;

CREATE INDEX IF NOT EXISTS soul_recovery_codes_hash_idx
  ON soul_recovery_codes (code_hash)
  WHERE used_at IS NULL;

-- Rate limit: emissão admin + consumo público.
ALTER TABLE auth_rate_events
  DROP CONSTRAINT IF EXISTS auth_rate_events_action_check;

ALTER TABLE auth_rate_events
  ADD CONSTRAINT auth_rate_events_action_check
  CHECK (action IN (
    'login',
    'register',
    'legacy_bind',
    'soul_recovery_issue',
    'soul_recovery_consume'
  ));
