-- Habilita extensão para hashing (opcional)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Tabela de usuários
CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name text NOT NULL,
  turma text NOT NULL CHECK (turma IN ('TCG01', 'TCG02')),
  username text UNIQUE NOT NULL,
  email text,
  email_verified_at timestamptz,
  password_hash text NOT NULL,
  role text NOT NULL DEFAULT 'student',
  xp integer NOT NULL DEFAULT 0,
  conquistas text[] NOT NULL DEFAULT '{}',
  completed_lessons text[] NOT NULL DEFAULT '{}',
  redeemed_codes text[] NOT NULL DEFAULT '{}',
  avatar_index integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT users_email_verified_requires_email_chk
    CHECK (email_verified_at IS NULL OR email IS NOT NULL),
  CONSTRAINT users_email_nonempty_chk
    CHECK (email IS NULL OR char_length(btrim(email)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_uidx
  ON users (lower(email))
  WHERE email IS NOT NULL AND btrim(email) <> '';

-- Tabela de sessões simples (tokens opacos) — TTL 14 dias (Task 2)
CREATE TABLE IF NOT EXISTS sessions (
  token text PRIMARY KEY,
  user_id integer REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '14 days')
);

CREATE INDEX IF NOT EXISTS sessions_expires_at_idx
  ON sessions (expires_at);

-- Rate limit de login/register/legado (Tasks 2 + 4)
CREATE TABLE IF NOT EXISTS auth_rate_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action text NOT NULL CHECK (action IN ('login', 'register', 'legacy_bind')),
  ip_hash text NOT NULL,
  username_hash text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS auth_rate_events_ip_created_idx
  ON auth_rate_events (action, ip_hash, created_at DESC);

CREATE INDEX IF NOT EXISTS auth_rate_events_user_created_idx
  ON auth_rate_events (action, username_hash, created_at DESC)
  WHERE username_hash IS NOT NULL;

-- Tabela de códigos de resgate (histórico)
-- O código é compartilhado pela turma: `redeemed_at`/`redeemed_by` registram apenas o
-- primeiro resgate (telemetria). A única trava de invalidação é `expires_at`.
CREATE TABLE IF NOT EXISTS redeem_codes (
  code text PRIMARY KEY,
  lesson_id text NOT NULL,
  lesson_title text NOT NULL,
  xp integer NOT NULL CHECK (xp > 0),
  created_by integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '20 minutes'),
  redeemed_by integer REFERENCES users(id) ON DELETE SET NULL,
  redeemed_at timestamptz NULL,
  CONSTRAINT redeem_codes_code_len_chk CHECK (char_length(code) = 7),
  CONSTRAINT redeem_codes_code_upper_alnum_chk CHECK (code ~ '^[A-Z0-9]{7}$')
);

CREATE INDEX IF NOT EXISTS redeem_codes_lesson_created_idx ON redeem_codes (lesson_id, created_at DESC);
CREATE INDEX IF NOT EXISTS redeem_codes_active_idx ON redeem_codes (lesson_id, expires_at DESC);

-- Tabela de gates de conteúdo por aula (censura/liberação por admin)
CREATE TABLE IF NOT EXISTS lesson_gates (
  lesson_id text NOT NULL,
  gate_key text NOT NULL,
  released boolean NOT NULL DEFAULT false,
  released_by integer REFERENCES users(id) ON DELETE SET NULL,
  released_at timestamptz NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (lesson_id, gate_key)
);

CREATE INDEX IF NOT EXISTS lesson_gates_lesson_idx ON lesson_gates (lesson_id);

-- Parágrafo de GDD por aluno e por aula
CREATE TABLE IF NOT EXISTS lesson_paragraphs (
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  lesson_id text NOT NULL,
  paragraph text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, lesson_id)
);

CREATE INDEX IF NOT EXISTS lesson_paragraphs_lesson_idx ON lesson_paragraphs (lesson_id);

-- Registro de visualizações de aula por aluno
CREATE TABLE IF NOT EXISTS lesson_views (
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  lesson_id text NOT NULL,
  first_viewed_at timestamptz NOT NULL DEFAULT now(),
  last_viewed_at timestamptz NOT NULL DEFAULT now(),
  view_count integer NOT NULL DEFAULT 1,
  PRIMARY KEY (user_id, lesson_id)
);

CREATE INDEX IF NOT EXISTS lesson_views_lesson_idx ON lesson_views (lesson_id, last_viewed_at DESC);

-- Vínculos entre alunos (Companheiros de Jornada)
CREATE TABLE IF NOT EXISTS friendships (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  addressee_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'accepted')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT friendships_no_self_chk CHECK (requester_id <> addressee_id),
  CONSTRAINT friendships_pair_uidx UNIQUE (requester_id, addressee_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS friendships_unordered_pair_uidx
  ON friendships (LEAST(requester_id, addressee_id), GREATEST(requester_id, addressee_id));

CREATE INDEX IF NOT EXISTS friendships_requester_status_idx
  ON friendships (requester_id, status);

CREATE INDEX IF NOT EXISTS friendships_addressee_status_idx
  ON friendships (addressee_id, status);

-- Grimório Pessoal
CREATE TABLE IF NOT EXISTS user_notes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title text NOT NULL,
  body text NOT NULL DEFAULT '',
  pinned boolean NOT NULL DEFAULT false,
  tags jsonb NOT NULL DEFAULT '[]'::jsonb,
  lesson_id text NULL,
  cloned_from_note_id integer REFERENCES user_notes(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_notes_title_len_chk CHECK (char_length(title) BETWEEN 1 AND 120),
  CONSTRAINT user_notes_body_len_chk CHECK (char_length(body) <= 8000)
);

CREATE INDEX IF NOT EXISTS user_notes_user_updated_idx
  ON user_notes (user_id, pinned DESC, updated_at DESC);

CREATE INDEX IF NOT EXISTS user_notes_user_lesson_idx
  ON user_notes (user_id, lesson_id);

CREATE INDEX IF NOT EXISTS user_notes_cloned_from_idx
  ON user_notes (cloned_from_note_id)
  WHERE cloned_from_note_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS user_note_shares (
  note_id integer NOT NULL REFERENCES user_notes(id) ON DELETE CASCADE,
  shared_with_user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (note_id, shared_with_user_id)
);

CREATE INDEX IF NOT EXISTS user_note_shares_viewer_idx
  ON user_note_shares (shared_with_user_id, note_id);

CREATE TABLE IF NOT EXISTS user_note_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note_id integer NOT NULL REFERENCES user_notes(id) ON DELETE CASCADE,
  actor_user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  read_at timestamptz NULL,
  CONSTRAINT user_note_events_kind_chk CHECK (
    kind IN ('veiled_by_recipient', 'cloned_by', 'veiled_by_owner')
  )
);

CREATE INDEX IF NOT EXISTS user_note_events_note_created_idx
  ON user_note_events (note_id, created_at DESC);

CREATE INDEX IF NOT EXISTS user_note_events_note_unread_idx
  ON user_note_events (note_id)
  WHERE read_at IS NULL;

-- Tokens de verificação de e-mail e reset de Palavra de Passagem
CREATE TABLE IF NOT EXISTS auth_email_tokens (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  purpose text NOT NULL
    CHECK (purpose IN ('reset_password', 'verify_email', 'legacy_reset')),
  token_hash text NOT NULL UNIQUE,
  email text NOT NULL,
  requested_ip text NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS auth_email_tokens_user_purpose_created_idx
  ON auth_email_tokens (user_id, purpose, created_at DESC);

CREATE INDEX IF NOT EXISTS auth_email_tokens_expires_idx
  ON auth_email_tokens (expires_at);

CREATE INDEX IF NOT EXISTS auth_email_tokens_email_purpose_created_idx
  ON auth_email_tokens (lower(email), purpose, created_at DESC);

CREATE INDEX IF NOT EXISTS auth_email_tokens_ip_created_idx
  ON auth_email_tokens (requested_ip, created_at DESC)
  WHERE requested_ip IS NOT NULL;

-- Audit de mutações do Mestre (Espelho da Alma — Task 7)
CREATE TABLE IF NOT EXISTS admin_audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  target_user_id integer REFERENCES users(id) ON DELETE SET NULL,
  action text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS admin_audit_events_created_idx
  ON admin_audit_events (created_at DESC);

CREATE INDEX IF NOT EXISTS admin_audit_events_target_idx
  ON admin_audit_events (target_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS admin_audit_events_actor_idx
  ON admin_audit_events (actor_id, created_at DESC);

-- Senha do Caronte / settings opacos do Domínio (Task 4)
CREATE TABLE IF NOT EXISTS site_settings (
  key text PRIMARY KEY,
  value_hash text NOT NULL,
  rotated_at timestamptz NOT NULL DEFAULT now(),
  rotated_by integer REFERENCES users(id) ON DELETE SET NULL
);

-- Estado server-authoritative de Hades: O Despertar (Task 1)
CREATE TABLE IF NOT EXISTS despertar_states (
  user_id integer PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  souls numeric(38, 2) NOT NULL DEFAULT 0,
  obols numeric(38, 2) NOT NULL DEFAULT 0,
  mnemosyne numeric(38, 2) NOT NULL DEFAULT 0,
  lifetime_souls numeric(38, 2) NOT NULL DEFAULT 0,
  run_souls numeric(38, 2) NOT NULL DEFAULT 0,
  prestige_count integer NOT NULL DEFAULT 0,
  generators_state jsonb NOT NULL DEFAULT '{}'::jsonb,
  shiny_counts jsonb NOT NULL DEFAULT '{}'::jsonb,
  upgrades_state jsonb NOT NULL DEFAULT '[]'::jsonb,
  talents_state jsonb NOT NULL DEFAULT '[]'::jsonb,
  edu_logs_seen jsonb NOT NULL DEFAULT '[]'::jsonb,
  milestones jsonb NOT NULL DEFAULT '{}'::jsonb,
  verdicts integer NOT NULL DEFAULT 0,
  juizo_best_streak integer NOT NULL DEFAULT 0,
  juizo_current_streak integer NOT NULL DEFAULT 0,
  juizo_milestones_claimed jsonb NOT NULL DEFAULT '[]'::jsonb,
  verdict_purchases jsonb NOT NULL DEFAULT '[]'::jsonb,
  juizo_run jsonb NULL,
  last_sync_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT despertar_souls_nonneg CHECK (souls >= 0),
  CONSTRAINT despertar_obols_nonneg CHECK (obols >= 0),
  CONSTRAINT despertar_mnemosyne_nonneg CHECK (mnemosyne >= 0),
  CONSTRAINT despertar_verdicts_nonneg CHECK (verdicts >= 0),
  CONSTRAINT despertar_juizo_best_nonneg CHECK (juizo_best_streak >= 0),
  CONSTRAINT despertar_juizo_current_nonneg CHECK (juizo_current_streak >= 0)
);

ALTER TABLE despertar_states ENABLE ROW LEVEL SECURITY;
-- Sem policies de INSERT/UPDATE para anon/authenticated.
-- O backend usa SUPABASE_SERVICE_ROLE_KEY (bypass RLS), igual ao restante do Domínio.

-- Fase B / B3 + G4.3: RPC híbrida (persist + award). Espelho de
-- db/migrate-2026-09-22-despertar-shiny-counts.sql (coluna shiny_counts + CASE no patch).
CREATE OR REPLACE FUNCTION public.despertar_persist_and_award(
  p_user_id integer,
  p_patch jsonb,
  p_achievement_ids text[] DEFAULT '{}'::text[],
  p_xp_delta integer DEFAULT 0
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_patch jsonb := COALESCE(p_patch, '{}'::jsonb);
  v_state public.despertar_states%ROWTYPE;
  v_user_id integer;
  v_xp integer;
  v_conquistas text[];
  v_existing text[];
  v_fresh text[] := '{}'::text[];
  v_id text;
  v_xp_delta integer := GREATEST(COALESCE(p_xp_delta, 0), 0);
BEGIN
  IF p_user_id IS NULL THEN
    RAISE EXCEPTION 'p_user_id obrigatório' USING ERRCODE = '22023';
  END IF;

  UPDATE public.despertar_states AS ds
  SET
    souls = CASE WHEN v_patch ? 'souls' THEN (v_patch->>'souls')::numeric ELSE ds.souls END,
    obols = CASE WHEN v_patch ? 'obols' THEN (v_patch->>'obols')::numeric ELSE ds.obols END,
    mnemosyne = CASE WHEN v_patch ? 'mnemosyne' THEN (v_patch->>'mnemosyne')::numeric ELSE ds.mnemosyne END,
    lifetime_souls = CASE WHEN v_patch ? 'lifetime_souls' THEN (v_patch->>'lifetime_souls')::numeric ELSE ds.lifetime_souls END,
    run_souls = CASE WHEN v_patch ? 'run_souls' THEN (v_patch->>'run_souls')::numeric ELSE ds.run_souls END,
    prestige_count = CASE WHEN v_patch ? 'prestige_count' THEN (v_patch->>'prestige_count')::integer ELSE ds.prestige_count END,
    generators_state = CASE WHEN v_patch ? 'generators_state' THEN COALESCE(v_patch->'generators_state', '{}'::jsonb) ELSE ds.generators_state END,
    shiny_counts = CASE WHEN v_patch ? 'shiny_counts' THEN COALESCE(v_patch->'shiny_counts', '{}'::jsonb) ELSE ds.shiny_counts END,
    upgrades_state = CASE WHEN v_patch ? 'upgrades_state' THEN COALESCE(v_patch->'upgrades_state', '[]'::jsonb) ELSE ds.upgrades_state END,
    talents_state = CASE WHEN v_patch ? 'talents_state' THEN COALESCE(v_patch->'talents_state', '[]'::jsonb) ELSE ds.talents_state END,
    edu_logs_seen = CASE WHEN v_patch ? 'edu_logs_seen' THEN COALESCE(v_patch->'edu_logs_seen', '[]'::jsonb) ELSE ds.edu_logs_seen END,
    milestones = CASE WHEN v_patch ? 'milestones' THEN COALESCE(v_patch->'milestones', '{}'::jsonb) ELSE ds.milestones END,
    verdicts = CASE WHEN v_patch ? 'verdicts' THEN (v_patch->>'verdicts')::integer ELSE ds.verdicts END,
    juizo_best_streak = CASE WHEN v_patch ? 'juizo_best_streak' THEN (v_patch->>'juizo_best_streak')::integer ELSE ds.juizo_best_streak END,
    juizo_current_streak = CASE WHEN v_patch ? 'juizo_current_streak' THEN (v_patch->>'juizo_current_streak')::integer ELSE ds.juizo_current_streak END,
    juizo_milestones_claimed = CASE WHEN v_patch ? 'juizo_milestones_claimed' THEN COALESCE(v_patch->'juizo_milestones_claimed', '[]'::jsonb) ELSE ds.juizo_milestones_claimed END,
    verdict_purchases = CASE WHEN v_patch ? 'verdict_purchases' THEN COALESCE(v_patch->'verdict_purchases', '[]'::jsonb) ELSE ds.verdict_purchases END,
    juizo_run = CASE
      WHEN NOT (v_patch ? 'juizo_run') THEN ds.juizo_run
      WHEN v_patch->'juizo_run' IS NULL OR v_patch->'juizo_run' = 'null'::jsonb THEN NULL
      ELSE v_patch->'juizo_run'
    END,
    last_sync_at = CASE WHEN v_patch ? 'last_sync_at' THEN (v_patch->>'last_sync_at')::timestamptz ELSE ds.last_sync_at END,
    updated_at = CASE WHEN v_patch ? 'updated_at' THEN (v_patch->>'updated_at')::timestamptz ELSE now() END
  WHERE ds.user_id = p_user_id
  RETURNING * INTO v_state;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'despertar_state_missing for user_id=%', p_user_id USING ERRCODE = 'P0002';
  END IF;

  SELECT u.id, u.xp, COALESCE(u.conquistas, '{}'::text[])
  INTO v_user_id, v_xp, v_existing
  FROM public.users AS u
  WHERE u.id = p_user_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'user_missing for id=%', p_user_id USING ERRCODE = 'P0002';
  END IF;

  IF p_achievement_ids IS NOT NULL AND cardinality(p_achievement_ids) > 0 THEN
    FOREACH v_id IN ARRAY p_achievement_ids LOOP
      IF v_id IS NOT NULL
        AND length(btrim(v_id)) > 0
        AND NOT (v_id = ANY (v_existing))
        AND NOT (v_id = ANY (v_fresh))
      THEN
        v_fresh := array_append(v_fresh, v_id);
      END IF;
    END LOOP;

    IF cardinality(v_fresh) > 0 THEN
      UPDATE public.users
      SET
        xp = COALESCE(xp, 0) + v_xp_delta,
        conquistas = v_existing || v_fresh
      WHERE id = p_user_id
      RETURNING id, xp, conquistas
      INTO v_user_id, v_xp, v_conquistas;
    ELSE
      v_conquistas := v_existing;
    END IF;
  ELSE
    v_conquistas := v_existing;
  END IF;

  RETURN jsonb_build_object(
    'state', to_jsonb(v_state),
    'user', jsonb_build_object(
      'id', v_user_id,
      'xp', v_xp,
      'conquistas', to_jsonb(COALESCE(v_conquistas, '{}'::text[]))
    )
  );
END;
$$;

REVOKE ALL ON FUNCTION public.despertar_persist_and_award(integer, jsonb, text[], integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.despertar_persist_and_award(integer, jsonb, text[], integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.despertar_persist_and_award(integer, jsonb, text[], integer) TO postgres;

-- Fase B / B5: placar SQL paginado (espelho de migrate-2026-09-22-leaderboard-page-rpc.sql)
CREATE OR REPLACE FUNCTION public.leaderboard_page(
  p_scope text DEFAULT 'turma',
  p_turma text DEFAULT NULL,
  p_sort text DEFAULT 'xp',
  p_limit integer DEFAULT 50,
  p_viewer_id integer DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_scope text := lower(coalesce(nullif(btrim(p_scope), ''), 'turma'));
  v_sort text := coalesce(nullif(btrim(p_sort), ''), 'xp');
  v_limit integer := GREATEST(1, LEAST(COALESCE(p_limit, 50), 200));
  v_turma text := nullif(btrim(p_turma), '');
  v_entries jsonb;
  v_self jsonb;
  v_total integer := 0;
BEGIN
  IF v_scope NOT IN ('turma', 'global') THEN
    v_scope := 'turma';
  END IF;
  IF v_sort NOT IN ('xp', 'achievements', 'juizoBest') THEN
    v_sort := 'xp';
  END IF;

  IF v_scope = 'turma' AND v_turma IS NULL THEN
    RETURN jsonb_build_object(
      'entries', '[]'::jsonb,
      'self', NULL,
      'total', 0
    );
  END IF;

  WITH base AS (
    SELECT
      u.id AS user_id,
      u.username,
      u.full_name,
      u.turma,
      COALESCE(u.xp, 0)::integer AS xp,
      COALESCE(cardinality(u.conquistas), 0)::integer AS achievements,
      COALESCE(d.juizo_best_streak, 0)::integer AS juizo_best
    FROM public.users AS u
    LEFT JOIN public.despertar_states AS d ON d.user_id = u.id
    WHERE COALESCE(u.role, 'student') <> 'admin'
      AND (
        v_scope = 'global'
        OR u.turma = v_turma
      )
  ),
  ranked AS (
    SELECT
      b.*,
      COUNT(*) OVER ()::integer AS total_count,
      ROW_NUMBER() OVER (
        ORDER BY
          CASE v_sort
            WHEN 'achievements' THEN b.achievements
            WHEN 'juizoBest' THEN b.juizo_best
            ELSE b.xp
          END DESC,
          b.username ASC NULLS LAST,
          b.user_id ASC
      )::integer AS rank
    FROM base AS b
  )
  SELECT
    COALESCE(
      (
        SELECT jsonb_agg(
          jsonb_build_object(
            'rank', r.rank,
            'userId', r.user_id,
            'username', r.username,
            'fullName', r.full_name,
            'turma', r.turma,
            'xp', r.xp,
            'achievements', r.achievements,
            'juizoBest', r.juizo_best
          )
          ORDER BY r.rank
        )
        FROM ranked AS r
        WHERE r.rank <= v_limit
      ),
      '[]'::jsonb
    ),
    (
      SELECT jsonb_build_object(
        'rank', r.rank,
        'userId', r.user_id,
        'username', r.username,
        'fullName', r.full_name,
        'turma', r.turma,
        'xp', r.xp,
        'achievements', r.achievements,
        'juizoBest', r.juizo_best
      )
      FROM ranked AS r
      WHERE p_viewer_id IS NOT NULL AND r.user_id = p_viewer_id
      LIMIT 1
    ),
    COALESCE((SELECT r.total_count FROM ranked AS r LIMIT 1), 0)
  INTO v_entries, v_self, v_total;

  RETURN jsonb_build_object(
    'entries', v_entries,
    'self', v_self,
    'total', v_total
  );
END;
$$;

REVOKE ALL ON FUNCTION public.leaderboard_page(text, text, text, integer, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.leaderboard_page(text, text, text, integer, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.leaderboard_page(text, text, text, integer, integer) TO postgres;

-- ClassInd-dle (Aula 05 — Task 2): salas live + snapshot Realtime
CREATE TABLE IF NOT EXISTS classind_rooms (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL,
  host_user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  turma text NULL CHECK (turma IS NULL OR turma IN ('TCG01', 'TCG02')),
  phase text NOT NULL DEFAULT 'lobby'
    CHECK (phase IN ('lobby', 'voting', 'revealed', 'results', 'ranking', 'closed')),
  current_round_index integer NOT NULL DEFAULT 0
    CHECK (current_round_index >= 0),
  deck_id text NOT NULL DEFAULT 'aula5-v1',
  state_version bigint NOT NULL DEFAULT 0
    CHECK (state_version >= 0),
  settings jsonb NOT NULL DEFAULT '{"requireAllVotes":false}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT classind_rooms_code_fmt_chk CHECK (code ~ '^[A-Z0-9]{4,6}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS classind_rooms_code_uidx
  ON classind_rooms (code);

CREATE INDEX IF NOT EXISTS classind_rooms_host_idx
  ON classind_rooms (host_user_id);

CREATE INDEX IF NOT EXISTS classind_rooms_phase_updated_idx
  ON classind_rooms (phase, updated_at DESC);

ALTER TABLE classind_rooms ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS classind_rounds (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id uuid NOT NULL REFERENCES classind_rooms(id) ON DELETE CASCADE,
  round_index integer NOT NULL CHECK (round_index >= 0),
  payload_public jsonb NOT NULL DEFAULT '{}'::jsonb,
  payload_secret jsonb NOT NULL DEFAULT '{}'::jsonb,
  phase text NOT NULL DEFAULT 'voting'
    CHECK (phase IN ('voting', 'revealed')),
  revealed_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT classind_rounds_room_index_uidx UNIQUE (room_id, round_index)
);

CREATE INDEX IF NOT EXISTS classind_rounds_room_idx
  ON classind_rounds (room_id, round_index);

ALTER TABLE classind_rounds ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS classind_votes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  round_id uuid NOT NULL REFERENCES classind_rounds(id) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  choice text NOT NULL CHECK (choice IN ('A', 'B')),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT classind_votes_round_user_uidx UNIQUE (round_id, user_id)
);

CREATE INDEX IF NOT EXISTS classind_votes_round_idx
  ON classind_votes (round_id);

CREATE INDEX IF NOT EXISTS classind_votes_user_idx
  ON classind_votes (user_id);

ALTER TABLE classind_votes ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS classind_members (
  room_id uuid NOT NULL REFERENCES classind_rooms(id) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  joined_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (room_id, user_id)
);

CREATE INDEX IF NOT EXISTS classind_members_room_idx
  ON classind_members (room_id);

CREATE INDEX IF NOT EXISTS classind_members_user_idx
  ON classind_members (user_id);

ALTER TABLE classind_members ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS classind_live_snapshots (
  room_id uuid PRIMARY KEY REFERENCES classind_rooms(id) ON DELETE CASCADE,
  state_version bigint NOT NULL DEFAULT 0 CHECK (state_version >= 0),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE classind_live_snapshots REPLICA IDENTITY FULL;

CREATE INDEX IF NOT EXISTS classind_live_snapshots_updated_idx
  ON classind_live_snapshots (updated_at DESC);

ALTER TABLE classind_live_snapshots ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS classind_live_snapshots_select_public ON classind_live_snapshots;
CREATE POLICY classind_live_snapshots_select_public
  ON classind_live_snapshots
  FOR SELECT
  TO anon, authenticated
  USING (true);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    IF NOT EXISTS (
      SELECT 1
      FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime'
        AND schemaname = 'public'
        AND tablename = 'classind_live_snapshots'
    ) THEN
      ALTER PUBLICATION supabase_realtime ADD TABLE classind_live_snapshots;
    END IF;
  ELSE
    RAISE NOTICE 'Publication supabase_realtime ausente — habilite Realtime no dashboard do projeto.';
  END IF;
END $$;

-- Inserir ADMIN (use a função crypt para gerar hash com pgcrypto)
-- Substitua a senha abaixo por uma segura ou execute o INSERT via painel SQL do Supabase
INSERT INTO users (full_name, turma, username, password_hash, role, xp, conquistas, completed_lessons, redeemed_codes, avatar_index)
VALUES (
  'Von Luqi',
  'TCG01',
  'VonLuqi',
  crypt('TaciLucas2002@', gen_salt('bf')),
  'admin',
  0,
  '{}',
  '{}',
  '{}',
  0
)
ON CONFLICT (username) DO NOTHING;

-- Observação: se o seu provedor não tiver pgcrypto, insira a senha em texto plano apenas para dev,
-- ou gere o hash em Node.js e atualize o registro.
