-- Habilita extensão para hashing (opcional)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Tabela de usuários
CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name text NOT NULL,
  turma text NOT NULL CHECK (turma IN ('TCG01', 'TCG02')),
  username text UNIQUE NOT NULL,
  password_hash text NOT NULL,
  role text NOT NULL DEFAULT 'student',
  xp integer NOT NULL DEFAULT 0,
  conquistas text[] NOT NULL DEFAULT '{}',
  completed_lessons text[] NOT NULL DEFAULT '{}',
  redeemed_codes text[] NOT NULL DEFAULT '{}',
  avatar_index integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Tabela de sessões simples (tokens opacos)
CREATE TABLE IF NOT EXISTS sessions (
  token text PRIMARY KEY,
  user_id integer REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Tabela de códigos de resgate (histórico)
-- O código é compartilhado pela turma: `redeemed_at`/`redeemed_by` registram apenas o
-- primeiro resgate (telemetria). A única trava de invalidação é `expires_at`.
CREATE TABLE IF NOT EXISTS redeem_codes (
  code text PRIMARY KEY,
  lesson_id text NOT NULL,
  lesson_title text NOT NULL,
  xp integer NOT NULL CHECK (xp > 0),
  created_by integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '20 minutes'),
  redeemed_by integer REFERENCES users(id) ON DELETE SET NULL,
  redeemed_at timestamptz NULL,
  CONSTRAINT redeem_codes_code_len_chk CHECK (char_length(code) = 7),
  CONSTRAINT redeem_codes_code_upper_alnum_chk CHECK (code ~ '^[A-Z0-9]{7}$')
);

CREATE INDEX IF NOT EXISTS redeem_codes_lesson_created_idx ON redeem_codes (lesson_id, created_at DESC);
CREATE INDEX IF NOT EXISTS redeem_codes_active_idx ON redeem_codes (lesson_id, expires_at DESC);

-- Tabela de gates de conteúdo por aula (censura/liberação por admin)
CREATE TABLE IF NOT EXISTS lesson_gates (
  lesson_id text NOT NULL,
  gate_key text NOT NULL,
  released boolean NOT NULL DEFAULT false,
  released_by integer REFERENCES users(id) ON DELETE SET NULL,
  released_at timestamptz NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (lesson_id, gate_key)
);

CREATE INDEX IF NOT EXISTS lesson_gates_lesson_idx ON lesson_gates (lesson_id);

-- Parágrafo de GDD por aluno e por aula
CREATE TABLE IF NOT EXISTS lesson_paragraphs (
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  lesson_id text NOT NULL,
  paragraph text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, lesson_id)
);

CREATE INDEX IF NOT EXISTS lesson_paragraphs_lesson_idx ON lesson_paragraphs (lesson_id);

-- Registro de visualizações de aula por aluno
CREATE TABLE IF NOT EXISTS lesson_views (
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  lesson_id text NOT NULL,
  first_viewed_at timestamptz NOT NULL DEFAULT now(),
  last_viewed_at timestamptz NOT NULL DEFAULT now(),
  view_count integer NOT NULL DEFAULT 1,
  PRIMARY KEY (user_id, lesson_id)
);

CREATE INDEX IF NOT EXISTS lesson_views_lesson_idx ON lesson_views (lesson_id, last_viewed_at DESC);

-- Inserir ADMIN (use a função crypt para gerar hash com pgcrypto)
-- Substitua a senha abaixo por uma segura ou execute o INSERT via painel SQL do Supabase
INSERT INTO users (full_name, turma, username, password_hash, role, xp, conquistas, completed_lessons, redeemed_codes, avatar_index)
VALUES (
  'Von Luqi',
  'TCG01',
  'VonLuqi',
  crypt('TaciLucas2002@', gen_salt('bf')),
  'admin',
  0,
  '{}',
  '{}',
  '{}',
  0
)
ON CONFLICT (username) DO NOTHING;

-- Observação: se o seu provedor não tiver pgcrypto, insira a senha em texto plano apenas para dev,
-- ou gere o hash em Node.js e atualize o registro.
