-- Habilita extensão para hashing (opcional)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Tabela de usuários
CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name text NOT NULL,
  turma text NOT NULL CHECK (turma IN ('TCG01', 'TCG02')),
  username text UNIQUE NOT NULL,
  email text,
  email_verified_at timestamptz,
  password_hash text NOT NULL,
  role text NOT NULL DEFAULT 'student',
  xp integer NOT NULL DEFAULT 0,
  conquistas text[] NOT NULL DEFAULT '{}',
  completed_lessons text[] NOT NULL DEFAULT '{}',
  redeemed_codes text[] NOT NULL DEFAULT '{}',
  avatar_index integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT users_email_verified_requires_email_chk
    CHECK (email_verified_at IS NULL OR email IS NOT NULL),
  CONSTRAINT users_email_nonempty_chk
    CHECK (email IS NULL OR char_length(btrim(email)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_uidx
  ON users (lower(email))
  WHERE email IS NOT NULL AND btrim(email) <> '';

-- Tabela de sessões simples (tokens opacos)
CREATE TABLE IF NOT EXISTS sessions (
  token text PRIMARY KEY,
  user_id integer REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Tabela de códigos de resgate (histórico)
-- O código é compartilhado pela turma: `redeemed_at`/`redeemed_by` registram apenas o
-- primeiro resgate (telemetria). A única trava de invalidação é `expires_at`.
CREATE TABLE IF NOT EXISTS redeem_codes (
  code text PRIMARY KEY,
  lesson_id text NOT NULL,
  lesson_title text NOT NULL,
  xp integer NOT NULL CHECK (xp > 0),
  created_by integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '20 minutes'),
  redeemed_by integer REFERENCES users(id) ON DELETE SET NULL,
  redeemed_at timestamptz NULL,
  CONSTRAINT redeem_codes_code_len_chk CHECK (char_length(code) = 7),
  CONSTRAINT redeem_codes_code_upper_alnum_chk CHECK (code ~ '^[A-Z0-9]{7}$')
);

CREATE INDEX IF NOT EXISTS redeem_codes_lesson_created_idx ON redeem_codes (lesson_id, created_at DESC);
CREATE INDEX IF NOT EXISTS redeem_codes_active_idx ON redeem_codes (lesson_id, expires_at DESC);

-- Tabela de gates de conteúdo por aula (censura/liberação por admin)
CREATE TABLE IF NOT EXISTS lesson_gates (
  lesson_id text NOT NULL,
  gate_key text NOT NULL,
  released boolean NOT NULL DEFAULT false,
  released_by integer REFERENCES users(id) ON DELETE SET NULL,
  released_at timestamptz NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (lesson_id, gate_key)
);

CREATE INDEX IF NOT EXISTS lesson_gates_lesson_idx ON lesson_gates (lesson_id);

-- Parágrafo de GDD por aluno e por aula
CREATE TABLE IF NOT EXISTS lesson_paragraphs (
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  lesson_id text NOT NULL,
  paragraph text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, lesson_id)
);

CREATE INDEX IF NOT EXISTS lesson_paragraphs_lesson_idx ON lesson_paragraphs (lesson_id);

-- Registro de visualizações de aula por aluno
CREATE TABLE IF NOT EXISTS lesson_views (
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  lesson_id text NOT NULL,
  first_viewed_at timestamptz NOT NULL DEFAULT now(),
  last_viewed_at timestamptz NOT NULL DEFAULT now(),
  view_count integer NOT NULL DEFAULT 1,
  PRIMARY KEY (user_id, lesson_id)
);

CREATE INDEX IF NOT EXISTS lesson_views_lesson_idx ON lesson_views (lesson_id, last_viewed_at DESC);

-- Vínculos entre alunos (Companheiros de Jornada)
CREATE TABLE IF NOT EXISTS friendships (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  addressee_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'accepted')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT friendships_no_self_chk CHECK (requester_id <> addressee_id),
  CONSTRAINT friendships_pair_uidx UNIQUE (requester_id, addressee_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS friendships_unordered_pair_uidx
  ON friendships (LEAST(requester_id, addressee_id), GREATEST(requester_id, addressee_id));

CREATE INDEX IF NOT EXISTS friendships_requester_status_idx
  ON friendships (requester_id, status);

CREATE INDEX IF NOT EXISTS friendships_addressee_status_idx
  ON friendships (addressee_id, status);

-- Grimório Pessoal
CREATE TABLE IF NOT EXISTS user_notes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title text NOT NULL,
  body text NOT NULL DEFAULT '',
  pinned boolean NOT NULL DEFAULT false,
  tags jsonb NOT NULL DEFAULT '[]'::jsonb,
  lesson_id text NULL,
  cloned_from_note_id integer REFERENCES user_notes(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_notes_title_len_chk CHECK (char_length(title) BETWEEN 1 AND 120),
  CONSTRAINT user_notes_body_len_chk CHECK (char_length(body) <= 8000)
);

CREATE INDEX IF NOT EXISTS user_notes_user_updated_idx
  ON user_notes (user_id, pinned DESC, updated_at DESC);

CREATE INDEX IF NOT EXISTS user_notes_user_lesson_idx
  ON user_notes (user_id, lesson_id);

CREATE INDEX IF NOT EXISTS user_notes_cloned_from_idx
  ON user_notes (cloned_from_note_id)
  WHERE cloned_from_note_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS user_note_shares (
  note_id integer NOT NULL REFERENCES user_notes(id) ON DELETE CASCADE,
  shared_with_user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (note_id, shared_with_user_id)
);

CREATE INDEX IF NOT EXISTS user_note_shares_viewer_idx
  ON user_note_shares (shared_with_user_id, note_id);

CREATE TABLE IF NOT EXISTS user_note_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note_id integer NOT NULL REFERENCES user_notes(id) ON DELETE CASCADE,
  actor_user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  read_at timestamptz NULL,
  CONSTRAINT user_note_events_kind_chk CHECK (
    kind IN ('veiled_by_recipient', 'cloned_by', 'veiled_by_owner')
  )
);

CREATE INDEX IF NOT EXISTS user_note_events_note_created_idx
  ON user_note_events (note_id, created_at DESC);

CREATE INDEX IF NOT EXISTS user_note_events_note_unread_idx
  ON user_note_events (note_id)
  WHERE read_at IS NULL;

-- Tokens de verificação de e-mail e reset de Palavra de Passagem
CREATE TABLE IF NOT EXISTS auth_email_tokens (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  purpose text NOT NULL
    CHECK (purpose IN ('reset_password', 'verify_email')),
  token_hash text NOT NULL UNIQUE,
  email text NOT NULL,
  requested_ip text NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS auth_email_tokens_user_purpose_created_idx
  ON auth_email_tokens (user_id, purpose, created_at DESC);

CREATE INDEX IF NOT EXISTS auth_email_tokens_expires_idx
  ON auth_email_tokens (expires_at);

CREATE INDEX IF NOT EXISTS auth_email_tokens_email_purpose_created_idx
  ON auth_email_tokens (lower(email), purpose, created_at DESC);

CREATE INDEX IF NOT EXISTS auth_email_tokens_ip_created_idx
  ON auth_email_tokens (requested_ip, created_at DESC)
  WHERE requested_ip IS NOT NULL;

-- Inserir ADMIN (use a função crypt para gerar hash com pgcrypto)
-- Substitua a senha abaixo por uma segura ou execute o INSERT via painel SQL do Supabase
INSERT INTO users (full_name, turma, username, password_hash, role, xp, conquistas, completed_lessons, redeemed_codes, avatar_index)
VALUES (
  'Von Luqi',
  'TCG01',
  'VonLuqi',
  crypt('TaciLucas2002@', gen_salt('bf')),
  'admin',
  0,
  '{}',
  '{}',
  '{}',
  0
)
ON CONFLICT (username) DO NOTHING;

-- Observação: se o seu provedor não tiver pgcrypto, insira a senha em texto plano apenas para dev,
-- ou gere o hash em Node.js e atualize o registro.
